### ISSUE TITLE
Невозможно закрыть диалоговое окно

### ISSUE THREAD

**Issue by myadzel** [wladich/nakarte#286]
Воспроизводится, когда окно больше по высоте, чем окно браузера.

**Comment by myadzel** [comment]
Простой вариант решения (на обсуждение).

Добавить:

```css
.alertify {
    overflow: auto;
} 
```

Убрать:

```css
.alertify .alert, .alertify .dialog {
    top: 50%;
    transform: translateY(-50%);
} 
```

**Comment by myadzel** [comment]
Либо добавить блок media queries, которые будут "выключать" прежнее позиционирование при определенной высоте окна.

**Comment by wladich** [comment]
Кажется, это дубль #209, который решен в зависшем PR #211 
Я его отребейзил в #290 и раскатил на stage.nakarte.me.

Я вижу 2 проблемы
1. (не критично, можно оставить) исходное положение скролла  внизу, т.е. начало сообщения не видно. У тебя случайно нет идеи как это пофиксить без яваскрипта? 
2. В Хроме на Андроиде, похоже есть баг: если диалог потаскать вверх-вниз, то сдвигается всё окно. При нажатии на Ok карта оказывается смещенной вверх (снизу пустая полоса) и нет возможности отобразить адресную строку. В Firefox этого бага нет, в эмуляции мобильного в DevTools тоже. Сломанная адресная строка это хуже, чем незакрывающийся диалог. Как это чинить я не знаю.

**Comment by myadzel** [comment]
1. Опытным путем нашел следующее (кстати, там важен delay в 0.5s иначе игнорируется правила, работает также с загрузкой страницы со слоем, а не только с последующим ее включением):

```css
.alertify .alert, .alertify .dialog {
    animation: scroll 0.5s;
    animation-fill-mode: forwards;
    overflow: auto;
    max-height: 100%;
}

@keyframes scroll {
    from {
        overflow: inherit;
        max-height: inherit;
    }
    to {
        overflow: auto;
        max-height: 100%;
    }
}
```

Сделаю PR.

**Comment by myadzel** [comment]
2. Скорее всего это из-за

```css
body {
    overflow: hidden;
}
```

Где это сейчас реально нужно?

**Comment by myadzel** [comment]
Проверил. Убрал overflow c документа, раздал с телефона интернет и зашел локально, все нормально работает.

**Comment by wladich** [comment]
Убрал overflow с body - по-прежнему скролится карта, но теперь только с третьего раза, т.е. 3 раза подёргать вверх-вниз и тогда карта уползает веврх

**Comment by wladich** [comment]
Вариант без overflow сейчас на staging

**Comment by wladich** [comment]
Димаю, может другую либу поискать...

**Comment by myadzel** [comment]
Это, скорее всего, баг с позиционированием в Chrome. 

Нашел, как исправить это:

```css
.alertify {
    height: 100%;
    width: 100%;
    left: 0;
    top: 0;
    position: fixed;
    overflow: hidden;
}
```

Целиком файл стилей будет выглядеть так:

```css
.alertify {
    z-index: 100000 !important;
    height: 100%;
    width: 100%;
    left: 0;
    top: 0;
    position: fixed;
    overflow: hidden;
}

.alertify .alert>*, .alertify .dialog>* {
    overflow-wrap: break-word;
}

.alertify .alert .msg, .alertify .dialog .msg {
    white-space: pre-line;
}

.alertify .alert, .alertify .dialog {
    animation: scroll 0.5s;
    animation-fill-mode: forwards;
    overflow: auto;
    max-height: 100%;
}

@keyframes scroll {
    from {
        overflow: inherit;
        max-height: inherit;
    }
    to {
        overflow: auto;
        max-height: 100%;
    }
}
```

Проверь, пожалуйста, тоже.
